version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout

      # Optional: Install any root-level dependencies if needed
      - run:
          name: Install Root Dependencies (if any)
          command: |
            if [ -f package.json ]; then
              npm install
            else
              echo "No root package.json found, skipping."
            fi

      # Build the backend
      - run:
          name: Build Backend
          command: |
            cd server
            npm install
            npm install -g typescript
            npm run build

      # Build the frontend
      - run:
          name: Build Frontend
          command: |
            cd client
            npm install
            npm run build -- --configuration=production

      # Archive backend files for deployment
      - run:
          name: Archive Backend Files
          command: |
            cd server
            zip -r backend.zip .
      - persist_to_workspace:
          root: .
          paths:
            - server/backend.zip
            - client/dist/spicestory

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout

      # Install required utilities and EB CLI (pinned version)
      - run:
          name: Install dependencies
          command: |
            set -e
            yum update -y
            yum install -y tar gzip zip unzip python3 python3-pip
            python3 -m pip install --upgrade pip
            python3 -m pip install awsebcli==3.20.3

      - attach_workspace:
          at: .

      - run:
          name: Configure AWS Credentials
          command: |
            mkdir -p ~/.aws
            {
              echo "[default]"
              echo "aws_access_key_id=$AWS_ACCESS_KEY_ID"
              echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY"
              echo "region=$AWS_REGION"
            } > ~/.aws/config

      - run:
          name: Deploy Backend to Elastic Beanstalk
          command: |
            cd server
            # Pipe 'n' to skip CodeCommit prompts in non-interactive environments
            echo n | eb init SpiceStory-Server --region $AWS_REGION
            eb use SpiceStory-env
            eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                      AWS_REGION=$AWS_REGION \
                      DB_HOST=$DB_HOST \
                      DB_NAME=$DB_NAME \
                      DB_USER=$DB_USER \
                      DB_PASSWORD=$DB_PASSWORD \
                      DB_PORT=$DB_PORT \
                      JWT_SECRET=$JWT_SECRET \
                      PORT=$PORT

            # Run eb deploy in the foreground with a 30-minute timeout
            eb deploy SpiceStory-env --timeout 30

      - run:
          name: Deploy Frontend to S3
          command: |
            aws s3 sync client/dist/spicestory s3://$FRONTEND_S3_BUCKET --delete

workflows:
  build_and_deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main